name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM tools
      run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy
    - name: Check code formatting
      run: clang-format --dry-run --Werror src/*.c
    - name: Lint code
      run: clang-tidy src/*.c
