name: Build and Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Add commands to install any other dependencies, if necessary

    - name: Build and run tests
      working-directory: ./tests
      run: |
        make clean
        make
